# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MessageDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageDialog(object):
    def setupUi(self, MessageDialog):
        MessageDialog.setObjectName("MessageDialog")
        MessageDialog.resize(204, 154)
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        MessageDialog.setFont(font)
        MessageDialog.setLayoutDirection(QtCore.Qt.RightToLeft)
        MessageDialog.setLocale(QtCore.QLocale(QtCore.QLocale.Persian, QtCore.QLocale.Iran))
        self.verticalLayout = QtWidgets.QVBoxLayout(MessageDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_message = QtWidgets.QLabel(MessageDialog)
        self.lbl_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_message.setObjectName("lbl_message")
        self.verticalLayout.addWidget(self.lbl_message)
        self.wgt_message_buttons = QtWidgets.QWidget(MessageDialog)
        self.wgt_message_buttons.setObjectName("wgt_message_buttons")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wgt_message_buttons)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_confirm = QtWidgets.QPushButton(self.wgt_message_buttons)
        self.btn_confirm.setObjectName("btn_confirm")
        self.horizontalLayout.addWidget(self.btn_confirm)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.wgt_message_buttons)
        self.wgt_question_buttons = QtWidgets.QWidget(MessageDialog)
        self.wgt_question_buttons.setObjectName("wgt_question_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.wgt_question_buttons)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_yes = QtWidgets.QPushButton(self.wgt_question_buttons)
        self.btn_yes.setObjectName("btn_yes")
        self.horizontalLayout_2.addWidget(self.btn_yes)
        self.btn_no = QtWidgets.QPushButton(self.wgt_question_buttons)
        self.btn_no.setObjectName("btn_no")
        self.horizontalLayout_2.addWidget(self.btn_no)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout.addWidget(self.wgt_question_buttons)

        self.retranslateUi(MessageDialog)
        QtCore.QMetaObject.connectSlotsByName(MessageDialog)

    def retranslateUi(self, MessageDialog):
        _translate = QtCore.QCoreApplication.translate
        MessageDialog.setWindowTitle(_translate("MessageDialog", "پیام"))
        self.lbl_message.setText(_translate("MessageDialog", "متن پیام"))
        self.btn_confirm.setText(_translate("MessageDialog", "تایید"))
        self.btn_yes.setText(_translate("MessageDialog", "بله"))
        self.btn_no.setText(_translate("MessageDialog", "خیر"))
